version: '3.7'

services:
  db:
    image: postgres
    container_name: task
    restart: always
    ports:
      - 5432:5432
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${HOST}
    volumes:
      - tasks:/data/postgres
  backend:
    container_name: 'backend'
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment: 
      - DATABASE_URL=postgres://zryfkvgdroehgy:29b50c1a50c4704f7bdecf2aff0ee5c76e64b04529a37304f09bec392c923074@ec2-34-239-241-121.compute-1.amazonaws.com:5432/d2tbs3id9qmvcv
      - JWT_SECRET=SECRET
  frontend:
    container_name: 'frontend'
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  tasks:
    driver: local