version: '3.9'
services:
  database-task:
    container_name: 'db_task'
    image: mysql:8.0.21
    restart: 'always'
    volumes:
      - .:/usr/app/
    cap_add:
      - SYS_NICE    
    ports:
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root 
      - TZ=America/Sao_Paulo
  backend:
    container_name: 'backend'
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - database-task
  frontend:
    container_name: 'frontend'
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

