version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres_task
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_task
    volumes:
      - task:/data/postgres

volumes:
  task:
    driver: local