version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres_task
    restart: always
    ports:
      - 5432:5432
    environment:
      - DB_USER=POSTGRES_USER
      - DB_PASSWORD=POSTGRES_PASSWORD
      - DB_NAME=POSTGRES_DB
    volumes:
      - task:/data/postgres

volumes:
  task:
    driver: local